---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exfiltration-via-exfiltration-over-alternative-protocol
  labels:
    app.kubernetes.io/name: exfiltration-via-exfiltration-over-alternative-protocol
    app.kubernetes.io/part-of: crowdstrike-demo
    app.kubernetes.io/created-by: crowdstrike
spec:
  selector:
    matchLabels:
      run: exfiltration-via-exfiltration-over-alternative-protocol
  replicas: 1
  template:
    metadata:
      labels:
        run: exfiltration-via-exfiltration-over-alternative-protocol
        app.kubernetes.io/name: exfiltration-via-exfiltration-over-alternative-protocol
        app.kubernetes.io/part-of: crowdstrike-demo
        app.kubernetes.io/created-by: crowdstrike
      annotations:
        sensor.falcon-system.crowdstrike.com/injection: enabled
    spec:
      containers:
        - name: app
          image: quay.io/crowdstrike/detection-container
          imagePullPolicy: Always
          command:
            - "/entrypoint.sh"
          args:
            - "./bin/Exfiltration_via_Exfiltration_Over_Alternative_Protocol.sh; tail -f /dev/null"
