---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defense-evasion-via-masquerading
  labels:
    app.kubernetes.io/name: defense-evasion-via-masquerading
    app.kubernetes.io/part-of: crowdstrike-demo
    app.kubernetes.io/created-by: crowdstrike
spec:
  selector:
    matchLabels:
      run: defense-evasion-via-masquerading
  replicas: 1
  template:
    metadata:
      labels:
        run: defense-evasion-via-masquerading
        app.kubernetes.io/name: defense-evasion-via-masquerading
        app.kubernetes.io/part-of: crowdstrike-demo
        app.kubernetes.io/created-by: crowdstrike
      annotations:
        sensor.falcon-system.crowdstrike.com/injection: enabled
    spec:
      containers:
        - name: app
          image: quay.io/crowdstrike/detection-container
          imagePullPolicy: Always
          command:
            - "/entrypoint.sh"
          args:
            - "./bin/Defense_Evasion_via_Masquerading.sh; tail -f /dev/null"
