# Application that continuously generates random detection in random intervals
# 
# Deployment
#    kubectl apply -f ~/demo-yamls/detection-random.yaml
# Tear Down
#    kubectl delete -f ~/demo-yamls/detection-random.yaml
#
# Learn more about detection container at https://github.com/CrowdStrike/detection-container
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection-random
spec:
  selector:
   matchLabels:
      run: detection-random
  replicas: 1
  template:
    metadata:
      labels:
        run: detection-random
    spec:
      containers:
          - name: app
            image: quay.io/crowdstrike/detection-container
            imagePullPolicy: Always
            command:
              - "/entrypoint.sh"
