# Application that generates single detection and hangs up
#
# Deployment
#    kubectl apply -f ~/demo-yamls/detection-single.yaml
# Tear Down
#    kubectl delete -f ~/demo-yamls/detection-single.yaml
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection-single
  labels:
    app.kubernetes.io/name: detection-single
    app.kubernetes.io/part-of: crowdstrike-demo
    app.kubernetes.io/created-by: crowdstrike
spec:
  selector:
    matchLabels:
      run: detection-single
  replicas: 1
  template:
    metadata:
      labels:
        run: detection-single
        app.kubernetes.io/name: detection-single
        app.kubernetes.io/part-of: crowdstrike-demo
        app.kubernetes.io/created-by: crowdstrike
      annotations:
        sensor.falcon-system.crowdstrike.com/injection: enabled
    spec:
      containers:
        - name: app
          image: ubuntu:latest
          imagePullPolicy: Always
          command:
            - "bash"
          args:
            - "-xc"
            - "chgrp 0 /etc/ld.so.preload; tail -f /dev/null"
