---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: malware-linux-trojan
spec:
  selector:
    matchLabels:
      run: malware-linux-trojan
  replicas: 1
  template:
    metadata:
      labels:
        run: malware-linux-trojan
      annotations:
        sensor.falcon-system.crowdstrike.com/injection: enabled
    spec:
      containers:
        - name: app
          image: quay.io/crowdstrike/detection-container
          imagePullPolicy: Always
          command:
            - "/entrypoint.sh"
          args:
            - "./bin/Malware_Linux_Trojan_Local.sh; tail -f /dev/null"
