# kubectl apply -f ~/.aws/share/vulnerable.example.yaml
# kubectl get service vulnerable-example-com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable.example.com
  labels:
    app.kubernetes.io/name: vulnerable.example.com
    app.kubernetes.io/part-of: crowdstrike-demo
    app.kubernetes.io/created-by: crowdstrike
spec:
  selector:
    matchLabels:
      run: vulnerable.example.com
  replicas: 1
  template:
    metadata:
      labels:
        run: vulnerable.example.com
        app.kubernetes.io/name: vulnerable.example.com
        app.kubernetes.io/part-of: crowdstrike-demo
        app.kubernetes.io/created-by: crowdstrike
      annotations:
        sensor.falcon-system.crowdstrike.com/injection: enabled
    spec:
      containers:
        - name: app
          image: quay.io/slukasik/vulnapp
          imagePullPolicy: Always
          command:
            - "/entrypoint.sh"
          ports:
            - containerPort: 8080
              name: web

---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-example-com
  labels:
    app.kubernetes.io/name: vulnerable-example-com
    app.kubernetes.io/part-of: crowdstrike-demo
    app.kubernetes.io/created-by: crowdstrike
spec:
  selector:
    run: vulnerable.example.com
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
